FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
COPY api/package.json api/
COPY web/package.json web/

RUN npm ci

COPY web ./web

RUN npm run build -w web

FROM nginx:alpine

COPY --from=builder /app/web/dist /usr/share/nginx/html
COPY docker/nginx-web.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
